version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: "node:16"
    container_name: quizio-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
