version: '3.8'

services:
  ui:
    image: quizio-ui:latest
    container_name: quizio-ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - ${QUIZIO_UI_PORT:-3006}:80

networks:
  default:
    name: quizio